### ISSUE TITLE
RBG crystal chamber

### ISSUE THREAD

**Issue by FatherCool** [Protonerd/FX-SaberOS#26]
Has anyone used a standard 5mm rgb led to light their crystal chamber to mirror blade colour. I don't really want to run them parellel to the blade leds as they are running 1A per die whereas the 5mm led will only draw around 20mA per die?

How would I hook this up with FXsaberOS?

**Comment by jbkuma** [comment]
Parallel is fine. You just need to properly resistor you LEDs independently.

All of your power connections are actually in parallel or series to your
battery one way or another, some paths are just more complicated.

On Dec 9, 2017 8:34 AM, "FatherCool" <notifications@github.com> wrote:

Has anyone used a standard 5mm rgb led to light their crystal chamber to
mirror blade colour. I don't really want to run them parellel to the blade
leds as they are running 1A per die whereas the 5mm led will only draw
around 20mA per die?

How would I hook this up with FXsaberOS?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Protonerd/FX-SaberOS/issues/26>, or mute the thread

**Comment by Protonerd** [comment]
You can trust jbkuma's word on it. I tried, parallel drive will work. Do not forget, the voltage is parellel, the current is not.

**Comment by FatherCool** [comment]
True. 

I don't think that it will work in my case however looking at how I'm wiring the chassis as I am making a plug in chassis where the blade LED side of the circuit is left in the hilt. The crystal chamber will be on the removable portion so the crystal led won't have access to the individual blade LED feeds to be wired in parallel to them. I might have to just do a deactivated crystal as the switches will also be on the hilt side so won't be able to turn it on outside the saber, which arguably is more realistic anyway!

**Comment by shiryu55** [comment]
I'm also thinking how to create crystal lighting,
put a led rgb, and light the color depending on the main color selection, and look just like efects of the lightsaber.

This would be possible. ??

**Comment by shiryu55** [comment]
fathercool , 
you are using a homebrew plate or a purchased for the chassis, I am trying to build a chassis for my graflex, if you want we could interambiar information for the creation of the chassis.

**Comment by FatherCool** [comment]
Hi I am designing the chassis as a bespoke unit for my saber. I am a 3D CAD designers by trade. I will get it 3D printed once complete. I don't know if it would be suitable for your build though as mine isn't a Graflex but a custom hilt that I made from machined aluminium and stainless steel exhaust pipe.

**Comment by shiryu55** [comment]
Any way, if you share your chassis , to take info, I would be grateful

**Comment by FatherCool** [comment]
No problem. I will post some info once it is done. It will have locations built into it to accept and hold the arduino nano v3.0, MPU-6050 and DFPlayer together with a 18650 battery.

**Comment by shiryu55** [comment]
ok , I  use a homebrew model.

**Comment by FatherCool** [comment]
Yes mine is homebrew also.

**Comment by shiryu55** [comment]
https://www.shapeways.com/product/D8ET7SSAD/graflex-2187-light-v2?optionId=60678043&li=marketplace


I would love to create something like that
