### ISSUE TITLE
neopixel

### ISSUE THREAD

**Issue by Himmiko** [Protonerd/FX-SaberOS#36]
Hello everyone, people!) which neopixels are you using? 
I bought one tape .. but it does not work. 
Requires too much power.

**Comment by jbkuma** [comment]
The pixels need about 20 to 40ma each (rated for 60ma @ 5v but less at
3.7v) depending on the color you use.  for 120 pixels x 2 strips that means
your battery needs to be able to deliver 6 to 10 amps.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by NobAkimoto** [comment]
I'm trying to set up a homebrew Nano + MPU6050 + DFPlayer Mini as a testbed to try out various configurations of neopixel blades so wanted to doublecheck something while we're on this subject - you don't need n-channel mosfets for doing a pixel blade, right? My understanding was that the D13 signal is what controls the settings on the pixels rather than the combination of FETs for LED-stars.

Is this correct?

**Comment by jbkuma** [comment]
You don't need them if you are connecting directly to the battery, but the
pixels will constantly draw power even when they aren't illuminated. The
transistor allows the board to manage power to the blade.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Himmiko** [comment]
Good. I have 2 18650 batteries. 
they hardly give out such quantity of a current....

**Comment by DRagonenko** [comment]
2 аккумулятора 18650 в параллельно и на прямую к neopixel и все  будет работать.
они работают от 2.8-5 В 
https://www.youtube.com/watch?v=y5QoS4JS1qM&feature=youtu.be
здесь 100диодов

**Comment by Himmiko** [comment]
я,похоже,какие-то не такие пиксели купил. у меня от аккумуляторов не работает. им нужно 10А тока.
http://led23.ru/catalog/lenty-rgb-begushchiy-ogon-178/lenta-spi-2-2500-5v-rgb-5x-5060-360ledx1-2812-w-017738.html

**Comment by faeton13** [comment]
​Судя паспорту там всего 5А на метр.
Какие симптомы не работающей ленты?
Подключена через транзисторы или напрямую?
В целом лента должна нормально работать и от одного акума. Идем в точку с
продажей расходников для вейперов, там есть батареи с токовыдачей под 30А.

With best regards.
Taras Protsiv
Additive Manufacturing Researcher

4 января 2018 г., 20:14 пользователь Олег Толстик <notifications@github.com>
написал:

**Comment by Himmiko** [comment]
Признаки? хмммм...ну во-первых она не горит)) ни от 1,ни от 2х аккумов. подключена напрямую,через транзисторы,через юсби от компа...как я ее только не подключал.. Батареи я уже заказал 10А,3.7в. Какие вы ленты используете? можно ссылочку?

**Comment by Himmiko** [comment]
кст..выпайка транзисторов из ленты помогает запустить 4-5 пикселей от 1 батареи.

**Comment by faeton13** [comment]
Транзисторов из ленты? О_о на ней ведь нет транзисторов... Может дело таки
не в питании а линии сигнала? Они не должны включаться без него.
Вобще разные использовал ws2812b обычно. Как раз арлайт должен иметь
совместимы чип.
100диодов по умолчанию в меня запускались от любого не севшего акума 18650
они выдают минимум 6а и этого обычно хватает для 100диодов. Косяки
начинаются после переключения цветов и попытках зажечь белый

On Jan 5, 2018 1:12 AM, "Олег Толстик" <notifications@github.com> wrote:

кст..выпайка транзисторов из ленты помогает запустить 4-5 пикселей от 1
батареи.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Protonerd/FX-SaberOS/issues/36#issuecomment-355413881>,
or mute the thread

**Comment by DRagonenko** [comment]
в ленте нету транзисторов. там стоят конденсаторы для работы.
от юсб ты тока штук 10 сможешь включить.
для питания нужно пару аккумов в параллели.

**Comment by Himmiko** [comment]
окей. придут попробую.

**Comment by Himmiko** [comment]
так..вы оказались правы) высокотоковые батареи справляются с этой лентой. все работает. единственная проблема-я не могу поменять цвет(при попытке шевелить прототипом,если происходит малейшее резкое движение,выходит из меню конфигураций). И после выхода из сна не работает звук. при перезагрезке платы-все окей

**Comment by Himmiko** [comment]
https://youtu.be/VtarNnmV-Ho

**Comment by Himmiko** [comment]
Так..цвет я поменял,все проблемы решены)
